### ISSUE TITLE
Annotations for last picture in a sequence missing

### ISSUE THREAD

**Issue by 9autilus** [govindnh4cl/caltech-pedestrian-dataset-converter#1]
The `convert_annotations.py` **might** be skipping the last picture's annotations.

**Comment by Almonfrey** [comment]
I **think** the problem is that in Caltech Pedestrian dataset the image index start from 0.

**Comment by 9autilus** [comment]
I believe I have solved this issue with 72689e8af724d686227911d376b9471ce435b493 commit. Closing it.
