### ISSUE TITLE
Missing .split('.')[0]

### ISSUE THREAD

**Issue by Almonfrey** [govindnh4cl/caltech-pedestrian-dataset-converter#2]
Hi, I think a ".split('.')[0]" is missing in some seq_name variables in the file convert_seqs.py. So, the script is generating .txt files with dirs VXXX.seq/ 

lines 48: filenamewithpath=os.path.join(outdir, set, seq_name.split('.')[0], filename)         
         51: print os.path.join(set, seq_name.split('.')[0], filename.split('.')[0])

**Comment by 9autilus** [comment]
Thank you. I have added this in 9bd6f5e570b09d4ec7e9e7b8686f532be5ac2082
