### ISSUE TITLE
Failed conversion

### ISSUE THREAD

**Issue by shehroze96** [govindnh4cl/caltech-pedestrian-dataset-converter#3]
For some reason when I run convert_seqs.py it only produces the directories but no images, I was wondering what I'm doing wrong can anyone help me?

**Comment by 9autilus** [comment]
I have corrected the issue with 9bd6f5e570b09d4ec7e9e7b8686f532be5ac2082 commit. Please try it now. Also it only works with Python2 (I have tested with Python 2.7). I am still figuring out why Python3 is breaking it.
